name: mapbox_turn_by_turn
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mapbox_navigation: ^0.0.26
  shared_preferences: ^2.0.13
  location: ^4.3.0
  google_fonts: ^2.3.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  mapbox_gl: ^0.15.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  geolocator: ^9.0.2
  toast: ^0.3.0
  flutter_native_splash: ^2.2.16
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.3
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.3.0
  syncfusion_flutter_charts: ^20.4.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  test: ^1.22.1

flutter_native_splash:
  color: "#FFFFFF"
  image_path: "assets/core/app_icon.png"
  android: true

flutter_icons:
  android: true
  color: "#FFFFFF"
  image_path: "assets/core/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
